// src/mockData/userData.ts
import { User } from '../types/models';

export const userData: User[] = [
  {
    id: 1,
    email: 'admin@sit.com',
    title: 'Mr.',
    firstName: 'Super',
    lastName: 'Admin',
    phone: '0811111111',
    institution: 'Smart Innovation School',
    province: 'Bangkok',
    emailVerified: true,
    adminVerified: true,
    emailVerifiedAt: new Date('2024-01-01T00:00:00Z'),
    adminVerifiedAt: new Date('2024-01-01T00:00:00Z'),
    isActive: true,
    createdAt: new Date('2024-01-01T00:00:00Z'),
    updatedAt: new Date('2024-01-01T00:00:00Z'),
    createdBy: null,
    updatedBy: null,
    roles: 'super_admin'
  },
  {
    id: 2,
    email: 'thirayu.m@gmail.com',
    title: 'Mrs.',
    firstName: 'Thirayu',
    lastName: 'Meererksom',
    phone: '0822222222',
    institution: 'Smart Innovation School',
    province: 'Bangkok',
    emailVerified: true,
    adminVerified: true,
    emailVerifiedAt: new Date('2024-01-02T00:00:00Z'),
    adminVerifiedAt: new Date('2024-01-02T00:00:00Z'),
    isActive: true,
    createdAt: new Date('2024-01-02T00:00:00Z'),
    updatedAt: new Date('2024-01-02T00:00:00Z'),
    createdBy: 1,
    updatedBy: 1,
    roles: 'admin'
  },
  {
    id: 3,
    email: 'staff1@school.com',
    title: 'Mr.',
    firstName: 'John',
    lastName: 'Staff',
    phone: '0833333333',
    institution: 'Smart Innovation School',
    province: 'Bangkok',
    emailVerified: false,
    adminVerified: false,
    emailVerifiedAt: null,
    adminVerifiedAt: null,
    isActive: false,
    createdAt: new Date('2024-01-03T00:00:00Z'),
    updatedAt: new Date('2024-01-03T00:00:00Z'),
    createdBy: 2,
    updatedBy: 2,
    roles: 'staff'
  },
  {
    id: 4,
    email: 'teacher1@school.com',
    title: 'Ms.',
    firstName: 'Sarah',
    lastName: 'Teacher',
    phone: '0844444444',
    institution: 'Smart Innovation School',
    province: 'Bangkok',
    emailVerified: false,
    adminVerified: false,
    emailVerifiedAt: null,
    adminVerifiedAt: null,
    isActive: false,
    createdAt: new Date('2024-01-04T00:00:00Z'),
    updatedAt: new Date('2024-01-04T00:00:00Z'),
    createdBy: 2,
    updatedBy: 2,
    roles: 'teacher'
  },
  {
    id: 5,
    email: 'teacher2@school.com',
    title: 'Mr.',
    firstName: 'Michael',
    lastName: 'Teacher',
    phone: '0855555555',
    institution: 'Smart Innovation School',
    province: 'Bangkok',
    emailVerified: false,
    adminVerified: false,
    emailVerifiedAt: null,
    adminVerifiedAt: null,
    isActive: false,
    createdAt: new Date('2024-01-05T00:00:00Z'),
    updatedAt: new Date('2024-01-05T00:00:00Z'),
    createdBy: 2,
    updatedBy: 2,
    roles: 'teacher'
  }
];